[package]
edition = "2018"
name = "chapter4"
version = "0.1.0"

[dependencies]
rocket = "0.5.0-rc.1"
serde = "1.0.130"
sqlx = {version = "0.5.7", features = ["postgres", "uuid", "runtime-tokio-rustls"]}
uuid = "0.8.2"
